version: "3.8"

services:
  # Servizio per l'app FastAPI
  fastapi-app:
    build:
      context: .
      dockerfile: "Docker"
    container_name: 15MinuteApp
    ports:
      - "8000:8000" # Mappa la porta 27017 del contenitore sulla porta 27017 del tuo host
    volumes:
    #in fase di testing per non dover riavviare il container
      - type: bind
        source: ./frontend
        target: /frontend
      - type: bind
        source: ./backend
        target: /backend
    depends_on:
      - mongodb
    environment:
      MONGO_URL: "mongodb://user:pass@mongodb:27017"
    networks:
      - app-network

  # Servizio per MongoDB
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    # sudo chmod -R 700 mongo_production/
    # sudo chown -R mirko:mirko mongo_production/
    user: "${UID}:${GID}"  # usa il tuo UID/GID
    volumes:
      - type: bind
        source: ./mongo_production/db
        target: /data/db
      - ./db_init/backup/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
